tbb GausHitFinder_module
LArSoft/larreco pull request #10
Opened 2020-04-02 16:35 UTC by cerati

This pull request changes the loop over wires in the GausHitFinder_module from a simple for loop to a tbb::parallel_for. Concurrent pushing of results in the output vector is handled via tbb::concurrent_vector. Credits to @sberkman for the initial implementation. Thread scaling performance is currently under study. The PR also includes a bug fix in the PeakFitterMrqdt_tool, so that the number of degrees of freedom (NDF) is now properly returned.

2020-04-02 16:36 UTC, FNALbuild commented
A new Pull Request was created by  @cerati  for develop.

It involves the following packages:

larreco


@LArSoft/level-1-managers, @LArSoft/level-2-managers can you please review it and eventually sign? Thanks.

cms-bot commands are listed <a href="https://cdcvs.fnal.gov/redmine/projects/larsoft/wiki/Pull_request_comments_that_trigger_CI_actions">here</a>

2020-04-02 16:36 UTC, FNALbuild commented
The code-checks are being triggered in jenkins.

2020-04-02 16:36 UTC, FNALbuild commented
-code-checks
Pull request failed trailing whitespace check.
Please setup larsoft and in the source directory run
```
curl -s -L https://patch-diff.githubusercontent.com/raw/LArSoft/larreco/pull/10.patch | grep '^diff --git ' | sed 's|.* a/||;s|  *b/.*||' | sort | uniq | tr '\n' ' ' > changed_files
removeWhiteSpace.sh < changed_files
```

2020-04-02 16:40 UTC, FNALbuild commented
Pull request #10 was updated. @LArSoft/level-1-managers, @LArSoft/level-2-managers can you please check and sign again.

2020-04-02 16:40 UTC, FNALbuild commented
The code-checks are being triggered in jenkins.

2020-04-02 16:41 UTC, FNALbuild commented
+code-checks  
 for details see 
 https://buildmaster.fnal.gov/buildmaster/job/GithubIntegration/job/run-pr-code-checks//485/console

2020-04-03 01:36 UTC, knoepfel requested changes
Relatively minor changes requested.  Looks good.

2020-04-03 01:36 UTC, knoepfel commented on larreco/HitFinder/GausHitFinder_module.cc
> +#include "tbb/blocked_range.h"
I suspect you can remove the `tbb/blocked_range` dependency.

2020-04-03 01:36 UTC, knoepfel commented on larreco/HitFinder/GausHitFinder_module.cc
> +		    hitstruct_vec.push_back(hitstruct_local);
Recommend more concise/efficient pattern:
```.cpp
hitstruct tmp{std::move(hit), wire};
hitstruct_vec.push_back(std::move(tmp));
```

2020-04-03 01:36 UTC, knoepfel commented on larreco/HitFinder/GausHitFinder_module.cc
> +			filthitstruct_vec.push_back(filthitstruct_local);
Recommend more concise/efficient pattern:
```.cpp
hitstruct tmp{std::move(filteredHit), wire};
filthitstruct_vec.push_back(std::move(tmp));
```

2020-04-03 02:38 UTC, FNALbuild commented
Pull request #10 was updated. @LArSoft/level-1-managers, @LArSoft/level-2-managers can you please check and sign again.

2020-04-03 02:39 UTC, FNALbuild commented
The code-checks are being triggered in jenkins.

2020-04-03 02:39 UTC, FNALbuild commented
+code-checks  
 for details see 
 https://buildmaster.fnal.gov/buildmaster/job/GithubIntegration/job/run-pr-code-checks//486/console

2020-04-03 02:41 UTC, cerati commented
@knoepfel's suggestions above are implemented in the last commit (thanks!)

2020-04-03 12:45 UTC, knoepfel approved these changes

2020-04-03 12:45 UTC, knoepfel commented
@cerati, looks good!

2020-04-03 12:46 UTC, knoepfel commented
approve

2020-04-03 12:46 UTC, FNALbuild commented
The tests are being triggered in jenkins.

2020-04-03 12:46 UTC, FNALbuild commented
This pull request is fully signed and it will be merged to develop and built in the next LArSoft release after it passes the integration tests.

2020-04-03 12:46 UTC, knoepfel commented
trigger build

2020-04-03 13:12 UTC, FNALbuild commented
+tests 
 for details see 
 https://lar-ci-history.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/8206&builds= 
 +build

2020-04-03 13:12 UTC, FNALbuild commented
+tests 
 for details see 
 https://lar-ci-history.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/8206&builds= 
 +build

2020-04-06 16:33 UTC, lgarren commented
trigger build

Previous CI tests did not include uboonecode, which is now updated.  Apparently sbndcode still lags behind.

2020-04-06 16:33 UTC, FNALbuild commented
The tests are being triggered in jenkins.

2020-04-06 17:03 UTC, FNALbuild commented
+tests 
 for details see 
 https://lar-ci-history.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/8212&builds= 
 +build

2020-04-06 17:05 UTC, FNALbuild commented
+tests 
 for details see 
 https://lar-ci-history.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/8212&builds= 
 +build

2020-04-06 19:53 UTC, lgarren commented
trigger build

Previous CI tests did not include uboonecode, which is now updated.  Apparently sbndcode still lags behind.

2020-04-06 19:53 UTC, FNALbuild commented
The tests are being triggered in jenkins.

2020-04-06 20:58 UTC, FNALbuild commented
+tests 
 for details see 
 https://lar-ci-history.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/8218&builds= 
 +build

2020-04-07 00:48 UTC, merged